# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

- name: Snyk
  # You may pin to the exact commit or the version.
  # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
  uses: snyk/actions@0.3.0
  with:
    # Which Snyk command to run, defaults to test
    command: # optional, default is test
    # Additional arguments to pass to Snyk
    args: # optional
    # Output a snyk.json file with results if running the test command
    json: # optional

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
